[TCHL-67][TCHL-75] Aggiunta ultimi due verbali esterni e aggiornamento README
Torchlight-SWE2324/Documentazione pull request #32
Opened 2024-01-11 01:27 UTC by FedeYe

Il verbale del 20 Dicembre è stato già verificato, serve una controllata su quello del 10 Gennaio.
Una volta fatta la verifica, li manderò assieme al proponente perché vengano approvati.

2024-01-11 13:46 UTC, giovannifil-64 requested changes
Vanno bene, uniche cose metterei la g del glossario anche sulla prima occorrenza di SQL nel verbale di ieri:
<img width="816" alt="Screenshot 2024-01-11 alle 14 43 33" src="https://github.com/Torchlight-SWE2324/Documentazione/assets/39963191/27a1c0d8-2a40-4aeb-9a50-815643852345">

Scriverei casi d'uso o use case, non andrei a usarli in maniera alternata (Verbale del 20 dicembre):
<img width="854" alt="Screenshot 2024-01-11 alle 14 44 13" src="https://github.com/Torchlight-SWE2324/Documentazione/assets/39963191/0f2cde06-316e-4e38-92c0-c61afaf6fd2c">

2024-01-11 14:43 UTC, giovannifil-64 approved these changes
LGTM

2024-01-11 15:48 UTC, FedeYe commented
Aspetto ad avere le versioni approvate dei verbali da Piccoli prima di fare il merge in main

2024-01-13 11:48 UTC, giovannifil-64 approved these changes
LGTM

2024-01-13 11:48 UTC, merged